version: '3'

services:
    freeradius:
        image: 'bustlec/freeradius'
        container_name: FreeRadius
        restart: always
        privileged: true
        ports:
          - 1812-1813:1812-1813/udp
        environment:
          - DB_HOST=db
          - RADIUS_CLIENT=0.0.0.0
          - RADIUS_SECRET=testing123
        depends_on:
          - "db"
    db:
        image: 'mysql'
        container_name: MySQL
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=dbpassword
          - MYSQL_DATABASE=radius
          - MYSQL_USER=radius
          - MYSQL_PASSWORD=radpass
        privileged: true
        ports:
          - 3306:3306
        volumes:
          #- ./db/data:/var/lib/mysql
          - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./initdb/sql:/opt/sql